name: Update JSON in GitHub Variable
on:
  push:
    branches:
      - feature/pradeep
  workflow_dispatch:
jobs:
  update_json:
    runs-on: ubuntu-latest
    env:
      TREX_DETAILS: ${{ vars.TREX_DETAILS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print existing JSON content
        run: |
          echo ${{ env.TREX_DETAILS }} >> current_trex_details.json
          jq '.is_registered = true' current_trex_details.json >> updated_trex_details.json
          echo $(cat updated_trex_details.json)

      - name: Update JSON
        run: |
          ENCODED_JSON=$(cat updated_trex_details.json)
          echo "UPDATED_JSON=$ENCODED_JSON" >> $GITHUB_ENV

      - name: Update GitHub variable
        run: |
          gh variable set TREX_DETAILS -b "$UPDATED_JSON" -R pradeepiimt/source-repo