name: Update JSON in GitHub Variable
on:
  push:
    branches:
      - feature/pradeep
  workflow_dispatch:
jobs:
  update_json:
    runs-on: ubuntu-latest
    env:
      TREX_DETAILS: ${{ vars.TREX_DETAILS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print existing JSON content
        run: |
          echo 'EXISTING_JSON: ${{ env.TREX_DETAILS }}'

      - name: Update JSON
        run: |
          # Use jq to update the JSON attribute
          UPDATED_JSON=echo "${{ env.TREX_DETAILS }}" | jq '.is_registered = true')
          echo 'UPDATED_JSON=$UPDATED_JSON' >> GITHUB_ENV
          echo 'Updated JSON is: ${{ env.UPDATED_JSON }}'

      - name: Update GitHub variable
        run: |
          echo $UPDATED_JSON | gh variable set TREX_DETAILS - 