name: access-gh-varaibles-json
on:
  push:
    branches:
      - feature/pradeep

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup jq
      run: sudo apt-get install -y jq

    - name: Save JSON variable to file
      run: |
        echo "${{ vars.JSON_DATA }}" > json_data.json

    - name: Get value of a JSON attribute
      id: get-json-value
      run: |
        region=$(jq -r '.region' json_data.json)
        echo "region=$region" >> $GITHUB_ENV
        # url=$(jq -r '.url' json_data.json)
        # echo "url=$url" >> $GITHUB_ENV
        # is_registered=$(jq -r '.is_registered' json_data.json)
        # echo "is_registered=$is_registered" >> $GITHUB_ENV


    - name: Use the JSON attribute value
      run: |
        echo "The value of region is ${{ env.region }}"
        # echo "The value of url is ${{ env.url }}"
        # echo "The value of is_registered is ${{ env.is_registered }}"
