name: Update JSON in GitHub Variable
on:
  push:
    branches:
      - feature/pradeep
  workflow_dispatch:
jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load existing JSON content
        run: |
          EXISTING_JSON= ${{ vars.TREX_DETAILS }}
          echo 'Existing JSON: toJson($EXISTING_JSON)'

      - name: Update JSON
        run: |
          # Use jq to update the JSON attribute
          UPDATED_JSON=$(echo $EXISTING_JSON | jq '.is_registered = true')
          echo "Updated JSON: $UPDATED_JSON"

      - name: Update GitHub variable
        run: |
          echo $UPDATED_JSON | gh secret set TREX_DETAILS -