name: Update JSON in GitHub Variable

on:
  push:
    branches:
      - feature/pradeep
  workflow_dispatch:

jobs:
  update_json:
    runs-on: ubuntu-latest
    env:
      TREX_DETAILS: '{"url": "reporting-hub-dev.cdn.ultiproservices.com","is_registered": false}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update is_registered attribute
        run: |
          updated_json='${{ env.TREX_DETAILS }}' | jq '.is_registered = true'
          echo "$updated_json" > updated_trex_details.json

      - name: Update TREX_DETAILS GitHub variable
        run: |
          echo "TREX_DETAILS_1=$(< updated_trex_details.json)" >> $GITHUB_ENV

      - name: Update GitHub variable
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const content = process.env.UPDATED_JSON;
            await github.rest.actions.createOrUpdateSecretForRepo({
              owner: 'pradeepiimt',
              repo: 'source-repo',
              secret_name: 'TREX_DETAILS',
              encrypted_value: Buffer.from(content).toString('base64'),
              key_id: context.key_id
            });
