name: Trigger Other Workflow
on:
  push:
    branches:
     - feature/pradeep
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Successful Step
        run: echo "This step is successful"
      # - name: Failing Step
      #   run: exit 1  # Deliberately fail this step
      - name: Another Successful Step
        run: echo "This step is also successful"I     
  trigger_new_workflow:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}
 
      - name: Checkout Target Repo
        uses: actions/checkout@v2
        with:
          token:  ${{ steps.generate-token.outputs.token }}
          repository: pradeepiimt/target-repo

      - name: Trigger Target Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token:  ${{ steps.generate-token.outputs.token }}
          event-type: trigger-other-workflow
          repository: pradeepiimt/target-repo
          client-payload: '{"github": ${{ toJson(github) }}}'
