name: Trigger Other Workflow
on:
  push:
    branches:
     - feature/pradeep
  workflow_run:
    workflows: ["name_of_dependent_workflow_in_other_repository"]
    types:
      - completed  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  trigger_new_workflow:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}
 
      # - name: Checkout Target Repo
      #   uses: actions/checkout@v2
      #   with:
      #     token:  ${{ steps.generate-token.outputs.token }}
      #     repository: pradeepiimt/target-repo
      - name: Trigger Target Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token:  ${{ steps.generate-token.outputs.token }}
          event-type: trigger-other-workflow
          repository: pradeepiimt/target-repo
          client-payload: '{"github": ${{ toJson(github) }}}'

  dependent_workflow_result:
    runs-on: ubuntu-latest
    needs: [trigger_new_workflow]
    steps:
      - name: Check result for Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
            echo "Dependent Workflow is success"
            exit 0
      - name: Check result for Failure
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Dependent Workflow is Failed"
          exit 1