name: Source Workflow
on:
  push:
    branches:
      - feature/pradeep

jobs:
  get_workflow_id:
    runs-on: ubuntu-latest
    outputs:
      workflow_id: ${{ steps.get_id.outputs.workflow_id }}
    steps:
      - name: Get Workflow ID
        id: get_id
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: 'pradeepiimt',
              repo: 'target-repo'
            });
            const targetWorkflow = workflows.find(workflow => workflow.path === '.github/workflows/target_workflow.yml');
            return { workflow_id: targetWorkflow.id };

  trigger_and_wait:
    runs-on: ubuntu-latest
    needs: get_workflow_id
    steps:
      - name: Trigger Target Workflow
        id: trigger
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/actions/workflows/:workflow_id/dispatches
          workflow_id: ${{ needs.get_workflow_id.outputs.workflow_id }}
          ref: ${{ github.ref }}
          inputs: '{"input_name": "input_value"}' # If the target workflow requires inputs
      
      - name: Wait for Target Workflow
        id: wait
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/actions/runs/:run_id
          run_id: ${{ steps.trigger.outputs.data.id }}
          repo: 'target-repo'
          owner: 'pradeepiimt'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check Workflow Status
        run: echo "The status of the target workflow is ${{ steps.wait.outputs.data.status }}"
      
      # Proceed with next steps based on workflow status
